# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cee6e86dbb27d075b8081340eb64b74245a6b9f2c4e60497b5beec0171dd13f7ab88edf213fac3a0c6f1f5be003f74cfb576eecd770c1a5c9e07f4a3916b525a

test:
  secret_key_base: 6298208d327a910ec8db0b3985e0da90e3ce77b4d527f0ff2af879979e558c730f6df86da8bca30fc4ac06a154635115134ca3628cba4cc7d7961f7a1ebf4bb8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
